// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type SentimentType string

const (
	SentimentTypePositive SentimentType = "positive"
	SentimentTypeNegative SentimentType = "negative"
)

func (e *SentimentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SentimentType(s)
	case string:
		*e = SentimentType(s)
	default:
		return fmt.Errorf("unsupported scan type for SentimentType: %T", src)
	}
	return nil
}

type NullSentimentType struct {
	SentimentType SentimentType
	Valid         bool // Valid is true if SentimentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSentimentType) Scan(value interface{}) error {
	if value == nil {
		ns.SentimentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SentimentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSentimentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SentimentType), nil
}

type Feedback struct {
	ID        int32
	CreatedAt pgtype.Timestamptz
	Sentiment SentimentType
	Message   pgtype.Text
}

type ReportRun struct {
	ReportDate    pgtype.Date
	WindowStart   pgtype.Timestamptz
	WindowEnd     pgtype.Timestamptz
	PositiveCount int32
	NegativeCount int32
	AsanaTaskGid  pgtype.Text
	CreatedAt     pgtype.Timestamptz
}
